# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "uas" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/media/shared" =
    { device = "/dev/disk/by-uuid/58e043e1-c58a-4d6d-9d7d-e41baf92dc7f";
      fsType = "btrfs";
      options = [ "subvol=@shared" "noatime" "space_cache=v2" "compress=zstd" "ssd" "discard=async" ];
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/58e043e1-c58a-4d6d-9d7d-e41baf92dc7f";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@" "noatime" "space_cache=v2" "compress=zstd" "ssd" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/58e043e1-c58a-4d6d-9d7d-e41baf92dc7f";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@home" "noatime" "space_cache=v2" "compress=zstd" "ssd" "discard=async" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/58e043e1-c58a-4d6d-9d7d-e41baf92dc7f";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@snapshots" "noatime" "space_cache=v2" "compress=zstd" "ssd" "discard=async" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/58e043e1-c58a-4d6d-9d7d-e41baf92dc7f";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@var" "noatime" "space_cache=v2" "compress=zstd" "ssd" "discard=async" ];
    };

#  fileSystems."/nix" =
#    { device = "/dev/disk/by-uuid/58e043e1-c58a-4d6d-9d7d-e41baf92dc7f";
#      fsType = "btrfs";
#      options = [ "subvol=@nixos/@nix" "noatime" "space_cache=v2" "compress=zstd" "ssd" "discard=async" ];
#    };

#  fileSystems."/gnu" =
#    { device = "/dev/disk/by-uuid/58e043e1-c58a-4d6d-9d7d-e41baf92dc7f";
#      fsType = "btrfs";
#      options = [ "subvol=@nixos/@gnu" "noatime" "space_cache=v2" "compress=zstd" "ssd" "discard=async" ];
#    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/58e043e1-c58a-4d6d-9d7d-e41baf92dc7f";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@swap" "noatime" "space_cache=v2" "compress=zstd" "ssd" "discard=async" ];
    };

  swapDevices = [{
    device = "/swap/swapfile";
    size = 16*1024; # Creates an 16GB swap file
   }];

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2211-E5D1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
